language: python
python:
  - "2.6"
# command to install dependenci
#export PYTHONPATH=/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages:$PYTHONPATH

install:
source ENV1/bin/activate
# command to run tests
script: python ENV1/mysite/manage.py test empresas
